# Generated by Django 2.1 on 2018-08-17 00:13

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('crossbot', '0002_auto_20180815_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='crosswordtime',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='crosswordtime',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crossbot.MyUser'),
        ),
        migrations.AlterField(
            model_name='easysudokutime',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='easysudokutime',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crossbot.MyUser'),
        ),
        migrations.AlterField(
            model_name='minicrosswordtime',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='minicrosswordtime',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crossbot.MyUser'),
        ),
        migrations.AlterField(
            model_name='queryshorthands',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crossbot.MyUser'),
        ),
        migrations.AlterField(
            model_name='slackuser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crossbot.MyUser'),
        ),
        migrations.AlterUniqueTogether(
            name='crosswordtime',
            unique_together={('user', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='easysudokutime',
            unique_together={('user', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='minicrosswordtime',
            unique_together={('user', 'date')},
        ),
    ]
