# Generated by Django 2.1.2 on 2018-10-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossbot', '0004_migrate_old_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbuser',
            name='image_url',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='cbuser',
            name='slack_fullname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
