# Generated by Django 2.1.2 on 2018-10-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossbot', '0007_add_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='crosswordtime',
            name='deleted',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='easysudokutime',
            name='deleted',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='minicrosswordtime',
            name='deleted',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='crosswordtime',
            unique_together={('user', 'date', 'deleted')},
        ),
        migrations.AlterUniqueTogether(
            name='easysudokutime',
            unique_together={('user', 'date', 'deleted')},
        ),
        migrations.AlterUniqueTogether(
            name='minicrosswordtime',
            unique_together={('user', 'date', 'deleted')},
        ),
    ]
