# Generated by Django 2.1.2 on 2018-10-29 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossbot', '0008_cbuser_hat_key'),
        ('crossbot', '0008_deleted_times'),
    ]

    operations = []
