# Generated by Django 2.1.2 on 2018-10-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossbot', '0009_merge_20181029_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crosswordtime',
            name='deleted',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='easysudokutime',
            name='deleted',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='minicrosswordtime',
            name='deleted',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
