# Generated by Django 2.1.2 on 2018-11-07 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossbot', '0011_cbuser_title_key'),
        ('crossbot', '0011_manage_predictor'),
    ]

    operations = [
    ]
