# Generated by Django 2.1.2 on 2018-11-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossbot', '0012_merge_20181107_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbuser',
            name='hat_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='cbuser',
            name='title_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='itemownershiprecord',
            name='item_key',
            field=models.CharField(max_length=40),
        ),
    ]
